import { expect, test } from '@playwright/test'

test('monsoon mechanisms synchronize three views, explain omissions and restore P0', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', (error) => errors.push(error.message))
  await page.goto('/')
  await page.getByRole('button', { name: '南亚夏季风', exact: true }).click()
  const views = page.locator('[data-source-id="monsoon:south-asia"]')
  await expect(views).toHaveCount(3)
  for (const view of await views.all()) await expect(view).toHaveAttribute('data-direction', 'southwest')
  await expect(page.locator('[data-monsoon-arrow="south-asia"]')).toHaveCount(2)
  const explorer = page.getByRole('region', { name: '季风机制探究' })
  await explorer.getByRole('checkbox', { name: '越赤道气流', exact: true }).uncheck()
  await expect(explorer.getByText('缺失机制：越赤道气流', { exact: true })).toBeVisible()
  for (const view of await views.all()) await expect(view).toHaveAttribute('data-direction', 'incomplete')
  await page.getByRole('button', { name: '撤销', exact: true }).click()
  for (const view of await views.all()) await expect(view).toHaveAttribute('data-direction', 'southwest')
  await explorer.getByRole('checkbox', { name: '季节移动', exact: true }).uncheck()
  await expect(explorer.getByText('缺失机制：季节移动', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: '东亚冬季风', exact: true }).click()
  for (const view of await page.locator('[data-source-id="monsoon:east-asia"]').all()) await expect(view).toHaveAttribute('data-direction', 'northwest')
  await explorer.getByRole('checkbox', { name: '季风地转偏向', exact: true }).uncheck()
  await expect(page.locator('[data-monsoon-arrow]')).toHaveCount(0)
  await page.getByRole('button', { name: '三圈环流全景', exact: true }).click()
  await expect(page.getByRole('slider', { name: '海陆差异强度' })).toHaveValue('0')
  await expect(page.locator('[data-source-id^="pressure-center:"]')).toHaveCount(0)
  await expect(page.locator('[data-source-id^="monsoon:"]')).toHaveCount(0)
  expect(errors).toEqual([])
})
