import { expect, type Page } from '@playwright/test'

export async function completeStudentLearning(page: Page) {
  const panel = page.getByRole('region', { name: '学生诊断任务' })
  const records = page.getByRole('region', { name: '本地学习记录' })
  await panel.getByLabel('气压梯度', { exact: true }).selectOption('low-to-high')
  await panel.getByRole('button', { name: '提交任务预测' }).click()
  await panel.getByRole('button', { name: '验证答案' }).click()
  await expect(panel.getByRole('status')).toContainText('气压梯度方向错误')
  await panel.getByLabel('气压梯度', { exact: true }).selectOption('high-to-low')
  await page.getByRole('combobox', { name: '自转方向' }).selectOption('-1')
  await panel.getByLabel('任务偏转').selectOption('left')
  await panel.getByLabel('气流去向').selectOption('southeast')
  await panel.getByLabel('风向来源').selectOption('northwest')
  await expect(panel.getByRole('img')).toHaveAttribute('aria-label', '气流箭头指向东南')
  await page.getByRole('slider', { name: '月份', exact: true }).fill('7')
  await panel.getByLabel('答案月份').fill('7')
  await page.getByRole('slider', { name: '海陆差异强度' }).fill('1')
  await panel.getByLabel('答案考虑海陆差异').check()
  await panel.getByRole('button', { name: '提交任务预测' }).click()
  await panel.getByRole('button', { name: '验证答案' }).click()
  await expect(panel.getByRole('status')).toContainText('答案正确')
  await panel.getByRole('button', { name: '揭示因果链' }).click()
  await expect(panel.getByText(/高压流向低压 →/)).toBeVisible()
  await expect(page.getByRole('region', { name: '气候关联' }).getByRole('status')).toContainText('7 月')
  await expect(records.getByRole('status')).toContainText('2 条')
  await page.reload()
  await expect(records.getByRole('status')).toContainText('2 条')
  const downloadEvent = page.waitForEvent('download')
  await records.getByRole('button', { name: '导出学习记录' }).click()
  const download = await downloadEvent
  expect(download.suggestedFilename()).toBe('circulation-learning.json')
  const stream = await download.createReadStream()
  expect(stream).not.toBeNull()
  const chunks: Buffer[] = []
  for await (const chunk of stream!) chunks.push(Buffer.from(chunk))
  const exported = JSON.parse(Buffer.concat(chunks).toString('utf8'))
  expect(exported.version).toBe(1)
  expect(exported.records).toHaveLength(2)
  expect(exported.records[1]).toEqual({ taskId: 'trade-wind', month: 7, correct: true, diagnosisCode: 'correct', evidenceObjectIds: ['wind-belt:trade-north', 'pressure-belt:subtropical-north'] })
  await records.getByRole('button', { name: '清除学习记录' }).click()
  await page.reload()
  await expect(records.getByRole('status')).toContainText('0 条')
  await page.evaluate(() => localStorage.setItem('circulation-learning-v1', '{broken'))
  await page.reload()
  await expect(records.getByRole('status')).toContainText('损坏记录已恢复')
  await panel.getByRole('button', { name: '提交任务预测' }).click()
  await panel.getByRole('button', { name: '验证答案' }).click()
  await expect(records.getByRole('status')).toContainText('1 条')
}
